### ISSUE TITLE
How to span?

### ISSUE THREAD

**Issue by annameide** [smrlo/molecule#2]
Hi, 
I would like to ask how I can span a div from col3 to col10. In the first two columns I do not want to have anything. 
In the screenshot is a 6 columns design, but in the code I use the 12 column framework. 
Is this possible with the framework?

!!! Centering it is not the solution, because at other places in the layout I need the div to start at col5 and span to ccol12. See second screenshot.

Any help is very much appreciated!

Best regards
Anna 

<img width="777" alt="Bildschirmfoto 2021-08-13 um 17 55 51" src="https://user-images.githubusercontent.com/46717848/129386344-1630fb3e-9d4c-417d-a491-0057b3d08526.png">

<img width="883" alt="Bildschirmfoto 2021-08-13 um 18 00 25" src="https://user-images.githubusercontent.com/46717848/129386902-b6543a48-4407-4971-96b7-a2178d188fb8.png">

**Comment by smrlo** [comment]
> I would like to ask how I can span a div from col3 to col10. In the first two columns I do not want to have anything.

You have to define how many columns you want to use. So in the case you mentioned, you create a block of 2 columns and leave it empty, then you create an 8 columns block (from col3 to col10) for your content, then again a block of 2 columns and leave it empty. See the code below:
```
<div class="container-full">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">Col 3 to 10</div>
    <div class="col-2"></div>
  </div>
</div>
```

> at other places in the layout I need the div to start at col5 and span to ccol12

Same as above, you first create a 4 columns block, then a 8 columns block  (col5 to ccol12). Code below:
```
<div class="container-full">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-8">Col 5 to 12</div>
  </div>
</div>
```

**Comment by annameide** [comment]
Dear SM, 

thank you for your fast answer! The solution you proposed, worked! And when sizing the window to mobile, the "empty space" just collapses  and does not take up any space, which is exactly how I wanted it to behave.  

Thank you a great lot!

Best regards 
Anna
